config/routes.rb
Rails.application.routes.draw do
  resources :contact_infos
  resources :users

  root 'application#Agandi'

end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
  #belongs_to :user
  #validates :email, length: { maximum:40 minmun:2 }

  #validates :email, length: { maximum: 140 }, Spresence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	#validates :Username, length: { maximum: 20 }
	#has_many :contact_infos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def Agandi
    render text: "Hallo, Agandi!"
    
  end

end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
  before_action :set_contact_info, only: [:show, :edit, :update, :destroy]

  # GET /contact_infos
  # GET /contact_infos.json
  def index
    @contact_infos = ContactInfo.all
  end

  # GET /contact_infos/1
  # GET /contact_infos/1.json
  def show
  end

  # GET /contact_infos/new
  def new
    @contact_info = ContactInfo.new
  end

  # GET /contact_infos/1/edit
  def edit
  end

  # POST /contact_infos
  # POST /contact_infos.json
  def create
    @contact_info = ContactInfo.new(contact_info_params)

    respond_to do |format|
      if @contact_info.save
        format.html { redirect_to @contact_info, notice: 'Contact info was successfully created.' }
        format.json { render :show, status: :created, location: @contact_info }
      else
        format.html { render :new }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_infos/1
  # PATCH/PUT /contact_infos/1.json
  def update
    respond_to do |format|
      if @contact_info.update(contact_info_params)
        format.html { redirect_to @contact_info, notice: 'Contact info was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_info }
      else
        format.html { render :edit }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_infos/1
  # DELETE /contact_infos/1.json
  def destroy
    @contact_info.destroy
    respond_to do |format|
      format.html { redirect_to contact_infos_url, notice: 'Contact info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_info
      @contact_info = ContactInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_info_params
      params.require(:contact_info).permit(:user_id, :telephone, :email, :resedence)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :password, :confirmPassword)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact_infos/_form.html.erb
<%= form_for(@contact_info) do |f| %>
  <% if @contact_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_info.errors.count, "error") %> prohibited this contact_info from being saved:</h2>

      <ul>
      <% @contact_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.number_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :resedence %><br>
    <%= f.text_field :resedence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_infos/edit.html.erb
<h1>Editing Contact Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_info %> |
<%= link_to 'Back', contact_infos_path %>

app/views/contact_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contact Infos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Resedence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_infos.each do |contact_info| %>
      <tr>
        <td><%= contact_info.user_id %></td>
        <td><%= contact_info.telephone %></td>
        <td><%= contact_info.email %></td>
        <td><%= contact_info.resedence %></td>
        <td><%= link_to 'Show', contact_info %></td>
        <td><%= link_to 'Edit', edit_contact_info_path(contact_info) %></td>
        <td><%= link_to 'Destroy', contact_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact info', new_contact_info_path %>

app/views/contact_infos/new.html.erb
<h1>New Contact Info</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_infos_path %>

app/views/contact_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @contact_info.user_id %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @contact_info.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_info.email %>
</p>

<p>
  <strong>Resedence:</strong>
  <%= @contact_info.resedence %>
</p>

<%= link_to 'Edit', edit_contact_info_path(@contact_info) %> |
<%= link_to 'Back', contact_infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


<%= link_to 'New User', new_user_path %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :confirmPassword %><br>
    <%= f.text_field :confirmPassword %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Password</th>
      <th>Confirmpassword</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.confirmPassword %></td>
        <td><%= link_to 'View', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Remove', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Confirmpassword:</strong>
  <%= @user.confirmPassword %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>